### ISSUE TITLE
Automated_covid_detector_validation: img_name is not defined

### ISSUE THREAD

**Issue by danielkinahan** [mr7495/COVID-CT-Code#4]
This notebook doesn't run because of this error. I can't figure out what you meant by img_name here as it has indeces.

NameError                                 Traceback (most recent call last)
<ipython-input-8-c12911687b6a> in <module>()
     15             full_add=os.path.join(r,file)
     16             if 'SR_2' in full_add: #Select only SR_2 folder
---> 17               index1=img_name.index('patient')
     18               index2=img_name.index('_SR')
     19               if 'covid' in full_add:

NameError: name 'img_name' is not defined

**Comment by mr7495** [comment]
Hi, the issue has been resolved. please run the code again

**Comment by danielkinahan** [comment]
The original name error is gone but I am getting this:
`---> 18               index2=full_add.index('_SR')
ValueError: substring not found`

After removing the underscore it performs correctly.

It should be noted that with my own trained models this seems to fail at 

`----> 8 net=keras.models.load_model(Path, custom_objects=custom_object)`

with the error:

`OSError: SavedModel file does not exist at: /drive/MyDrive/models/ResNet50V2-FPN-e5-fold1-01-0.8739.hdf5/{saved_model.pbtxt|saved_model.pb}`

Do you happen to know why it's expecting the .pb file instead?

**Comment by mr7495** [comment]
There was an error parsing the -SR value. It should be changed with SR- which is fixed now. You are getting this error because Keras can not find the specific trained model in the directory. Are you entering the model address correctly? What is the format of your trained model? If you can not resolve the error, please share your model through a google drive link so I can investigate why the error is happening?

**Comment by danielkinahan** [comment]
I am no longer getting this error today despite using the exact same input as above. It seems this happens to me at random when executing on Google Colab. I'll close this and let you know if I can ever come across this issue in a consistent manner.
